[package]
name = "arb-consensus-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

# Internal
arb-mel-types.workspace = true
arbos-types.workspace = true

# Alloy
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp = { workspace = true, features = ["derive"] }

# Reth
reth-libmdbx = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true

[features]
default = ["libmdbx"]
libmdbx = ["dep:reth-libmdbx"]
