[package]
name = "arb-consensus-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

# Internal
arb-mel-types.workspace = true
arbos-types.workspace = true

# Alloy
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp = { workspace = true, features = ["derive"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
reth-libmdbx = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
