[package]
name = "arb-errors"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arb-storage-errors = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["std"]
std = ["arb-storage-errors/std", "thiserror/std"]

[lints]
workspace = true
