[package]
name = "arb-blob-client"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
c-kzg.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true
thiserror.workspace = true

# Alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-beacon.workspace = true

# Internal
arb-parent-chain-client.workspace = true

[dev-dependencies]
alloy-rpc-types-eth.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock.workspace = true

[lints]
workspace = true
