# golangci-lint configuration

run:
  skip-dirs:
    - go-ethereum
    - fastcache

  timeout: 10m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck

linters:
  enable:
    - asciicheck  # check for non-ascii characters
    - errorlint   # enure error wrapping is safely done
    - gocritic    # check for certain simplifications
    - gofmt       # ensure code is formatted
    - gosec       # check for security concerns
    - nilerr      # ensure errors aren't mishandled
    - staticcheck # check for suspicious constructs
    - unused      # check for unused constructs

linters-settings:
  errcheck:
    # report when type assertions aren't checked for errors as in
    #         a := b.(MyStruct)
    #
    check-type-assertions: true

  gocritic:
    disabled-tags:
      - experimental
      - opinionated

    disabled-checks:
      - ifElseChain
      - assignOp
      - unlambda
      - exitAfterDefer

  gosec:
    excludes:
      - G404  # checks that random numbers are securely generated

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
