use std::collections::BTreeMap;
use std::fs;
use std::process::{Command, ExitCode, Stdio};

use anyhow::{Context, Result};

use super::workspace_root;

const RG_PATTERN: &str = r"ARBOS_VERSION_(10|11|20|30|31|40|41|50|MULTI_CONSTRAINT_FIX|60|MULTI_GAS_CONSTRAINTS|STYLUS_FIXES|STYLUS_CHARGING_FIXES|DIA)\b";

pub fn run() -> Result<ExitCode> {
    let root = workspace_root();
    let crates_dir = root.join("crates");

    let rg = which_rg();
    let raw = match rg {
        Some(rg_path) => match run_rg(&rg_path, &crates_dir, &root) {
            Ok(out) => out,
            Err(err) => {
                eprintln!("warning: rg invocation failed: {err:#}");
                String::new()
            }
        },
        None => {
            eprintln!("warning: `rg` not found on PATH; producing empty inventory");
            String::new()
        }
    };

    let entries = parse_rg_output(&raw);

    let plan_dir = root.join(".plan");
    fs::create_dir_all(&plan_dir).with_context(|| format!("create {}", plan_dir.display()))?;
    let out_path = plan_dir.join("gate-inventory.md");
    let body = render_inventory(&entries);
    fs::write(&out_path, body).with_context(|| format!("write {}", out_path.display()))?;

    println!(
        "wrote {} ({} entries grouped into {} files)",
        out_path.display(),
        entries.len(),
        group_files(&entries).len()
    );
    Ok(ExitCode::SUCCESS)
}

fn which_rg() -> Option<std::path::PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        for name in ["rg", "rg.exe"] {
            let candidate = dir.join(name);
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

fn run_rg(
    rg: &std::path::Path,
    crates_dir: &std::path::Path,
    cwd: &std::path::Path,
) -> Result<String> {
    // Run from workspace root with a relative target so vimgrep paths are relative.
    let rel_target = crates_dir
        .strip_prefix(cwd)
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|_| crates_dir.to_path_buf());
    let output = Command::new(rg)
        .args(["--vimgrep", RG_PATTERN])
        .arg(&rel_target)
        .current_dir(cwd)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .context("spawn rg")?;
    // rg exits 1 on no matches.
    if !output.status.success() && output.status.code() != Some(1) {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("rg exited with status {:?}: {stderr}", output.status);
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

#[derive(Debug, Clone)]
struct Entry {
    file: String,
    line: u32,
    snippet: String,
    gate: String,
}

fn parse_rg_output(raw: &str) -> Vec<Entry> {
    let mut out = Vec::new();
    for line in raw.lines() {
        if line.contains("/tests/") {
            continue;
        }
        if line.contains("arb-chainspec/src/lib.rs") {
            continue;
        }
        let mut parts = line.splitn(4, ':');
        let file = match parts.next() {
            Some(f) => f.to_string(),
            None => continue,
        };
        let line_no: u32 = match parts.next().and_then(|s| s.parse().ok()) {
            Some(n) => n,
            None => continue,
        };
        if parts.next().is_none() {
            continue;
        }
        let text = match parts.next() {
            Some(t) => t.trim().to_string(),
            None => continue,
        };
        let gate = extract_gate(&text);
        out.push(Entry {
            file,
            line: line_no,
            snippet: text,
            gate,
        });
    }
    out
}

fn extract_gate(snippet: &str) -> String {
    let idx = match snippet.find("ARBOS_VERSION_") {
        Some(i) => i,
        None => return String::from("ARBOS_VERSION_?"),
    };
    let tail = &snippet[idx..];
    let token: String = tail
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    token
}

fn group_files(entries: &[Entry]) -> BTreeMap<String, Vec<&Entry>> {
    let mut by_file: BTreeMap<String, Vec<&Entry>> = BTreeMap::new();
    for e in entries {
        by_file.entry(e.file.clone()).or_default().push(e);
    }
    for v in by_file.values_mut() {
        v.sort_by_key(|e| e.line);
    }
    by_file
}

fn render_inventory(entries: &[Entry]) -> String {
    let mut s = String::new();
    s.push_str("# ArbOS Version Gate Inventory\n\n");
    s.push_str(
        "Auto-generated by `cargo xtask regen-inventory`. Status fields are not preserved across regenerations; track status separately.\n\n",
    );
    s.push_str(&format!("**Total gates:** {}\n\n", entries.len()));

    let by_file = group_files(entries);
    s.push_str("---\n\n## Gate Table by File\n\n");
    for (file, ents) in &by_file {
        s.push_str(&format!("### {file}\n\n"));
        s.push_str("| Line | Gate | Snippet | Fixture path (planned) | Status |\n");
        s.push_str("|---|---|---|---|---|\n");
        for e in ents {
            let stem = file_stem_for(file);
            let version_tag = version_tag_for(&e.gate);
            let fixture = format!("arbos/gate_{stem}_{line}_{ver}.json", line = e.line, ver = version_tag);
            let snippet = truncate(&e.snippet, 80).replace('|', "\\|");
            s.push_str(&format!(
                "| {line} | {gate} | `{snippet}` | {fixture} | none |\n",
                line = e.line,
                gate = e.gate,
                snippet = snippet,
                fixture = fixture,
            ));
        }
        s.push('\n');
    }
    s
}

fn file_stem_for(path: &str) -> String {
    std::path::Path::new(path)
        .file_stem()
        .and_then(|s| s.to_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn version_tag_for(gate: &str) -> String {
    gate.strip_prefix("ARBOS_VERSION_")
        .map(|t| t.to_ascii_lowercase())
        .unwrap_or_else(|| gate.to_ascii_lowercase())
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        let mut out = s.chars().take(max).collect::<String>();
        out.push_str("...");
        out
    }
}
