[package]
name = "arb-storage"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arb-storage-errors = { workspace = true }
alloy-evm = { workspace = true, features = ["rpc"] }
alloy-primitives = { workspace = true, features = ["std", "map-foldhash"] }
revm = { workspace = true, features = ["optional_balance_check", "optional_eip3541", "optional_eip3607", "optional_priority_fee_check", "optional_eip7623", "optional_no_base_fee"] }
revm-database = { workspace = true }
revm-state = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arb-test-utils = { workspace = true }
revm-database-interface = { workspace = true }

[lints]
workspace = true
