services:
  node0:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id", "0",
        "--http-port", "8800",
        "--keyset-file", "/app/timeboost-keyset.json",
        "--stamp", "/tmp/timeboost.stamp",
        "--namespace", "412346",
        "--espresso-base-url", "http://espresso-dev-node:41000/v1/",
        "--espresso-websocket-url", "ws://espresso-dev-node:41000/v1/",
      ]
    environment:
      - RUST_LOG=timeboost=info,sailfish=error,cliquenet=error,robusta=info
      - TIMEBOOST_SAILFISH_PORT=8000
      - TIMEBOOST_DECRYPT_PORT=10000
      - TIMEBOOST_CERTIFIER_PORT=11000
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8000:8000"
      - "10000:10000"
      - "8800:8800"
      - "11000:11000"
      - "9000:9000"
      - "5000:5000"
    volumes:
      - ./timeboost-keyset.json:/app/timeboost-keyset.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nitro-timeboost
  node1:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id", "1",
        "--http-port", "8801",
        "--keyset-file", "/app/timeboost-keyset.json",
        "--stamp", "/tmp/timeboost.stamp",
        "--namespace", "412346",
        "--espresso-base-url", "http://host.docker.internal:41000/",
        "--espresso-websocket-url", "ws://host.docker.internal:41000/",
      ]
    environment:
      - RUST_LOG=timeboost=info,sailfish=error,cliquenet=error,rubusta=info
      - TIMEBOOST_SAILFISH_PORT=8001
      - TIMEBOOST_DECRYPT_PORT=10001
      - TIMEBOOST_CERTIFIER_PORT=11001
      - TIMEBOOST_RPC_PORT=8801
      - TIMEBOOST_METRICS_PORT=9001
    ports:
      - "8001:8001"
      - "10001:10001"
      - "8801:8801"
      - "11001:11001"
      - "9001:9001"
    volumes:
      - ./timeboost-keyset.json:/app/timeboost-keyset.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nitro-timeboost
  espresso-dev-node:
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:release-rc-20250623-p2
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
      - "$ESPRESSO_BUILDER_PORT:$ESPRESSO_BUILDER_PORT"
      - "$ESPRESSO_DEV_NODE_PORT:$ESPRESSO_DEV_NODE_PORT"
    environment:
      - ESPRESSO_BUILDER_PORT
      - ESPRESSO_DEPLOYER_ACCOUNT_INDEX
      - ESPRESSO_DEV_NODE_PORT
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_DATABASE_MAX_CONNECTIONS=25
      - ESPRESSO_DEV_NODE_EPOCH_HEIGHT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=/data/espresso
      - RUST_LOG=WARN
      - RUST_LOG_FORMAT
    volumes:
      - espresso_storage:/data/espresso
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nitro-timeboost
networks:
  nitro-timeboost:
    driver: bridge
    name: nitro-timeboost
volumes:
  espresso_storage: