[package]
name = "test-cases"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
digest = { version = "0.9.0", default-features = false }
hex-literal = "0.3.4"
num-bigint = { version = "0.4.4", default-features = false }
sha2 = { version = "0.9.9", default-features = false }
sha3 = { version = "0.9.1", default-features = false }

[workspace]
