[package]
name = "arb-parent-chain-client"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true

alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-transport.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
alloy-consensus = { workspace = true }
alloy-rpc-client = { workspace = true }

[lints]
workspace = true
