[package]
name = "arb-mel-types"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["std", "rlp"] }
alloy-rlp = { workspace = true, features = ["derive"] }
arbos-types.workspace = true

[lints]
workspace = true
