[package]
name = "arb-stylus"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# Internal
arbos = { workspace = true }
arb-chainspec = { workspace = true }
arb-primitives = { workspace = true }

# Alloy
alloy-primitives = { workspace = true, features = ["map-foldhash"] }

# Wasmer
wasmer = { workspace = true, features = ["sys", "cranelift"] }
wasmer-compiler = { workspace = true }
wasmer-types = { workspace = true }
wasmparser = { workspace = true }

nitro-prover = { workspace = true }
nitro-arbutil = { workspace = true }
nitro-brotli = { workspace = true, features = ["cc_brotli"] }

# Revm
revm = { workspace = true, features = ["optional_balance_check", "optional_eip3541", "optional_eip3607", "optional_priority_fee_check", "optional_eip7623", "optional_no_base_fee"] }

# Common
thiserror = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
lazy_static = { workspace = true }
eyre = { workspace = true }

[build-dependencies]
cc = { workspace = true }

[dev-dependencies]
arb-context = { workspace = true }
wat = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true
