[package]
name = "arb-stylus"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true }
arb-chainspec = { workspace = true }
arb-primitives = { workspace = true }
arbos = { workspace = true }
eyre = { workspace = true }
lazy_static = { workspace = true }
nitro-arbutil = { workspace = true }
parking_lot = { workspace = true }
revm = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wasmparser = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
nitro-brotli = { workspace = true, features = ["link"] }
nitro-prover = { workspace = true }
wasmer = { workspace = true, features = ["sys", "cranelift"] }
wasmer-compiler = { workspace = true }
wasmer-types = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
nitro-brotli = { workspace = true }

[build-dependencies]
cc = { workspace = true }

[dev-dependencies]
arb-context = { workspace = true }
proptest = { workspace = true }
wat = { workspace = true }

[lints]
workspace = true
