// Copyright 2021-2022, Offchain Labs, Inc.
// For license information, see https://github.com/OffchainLabs/nitro/blob/master/LICENSE.md
//
//go:build sp1
package main

import (
	"runtime/debug"
)

func gcTweaks() {
	// For some reason, GOGC environment variable has no affect on WASM binaries generated by go.
	// We will have to tweak GC parameters in code.
	debug.SetGCPercent(1023)
}

//go:wasmimport sp1 dump_elf
func dumpElf()
