#!/usr/bin/env bash
# This script runs the Espresso tests in ./system_tests only.
set -euo pipefail
gotestsum \
    --format short-verbose \
    --packages="github.com/offchainlabs/nitro/system_tests" \
    -- \
    -v \
    -timeout 35m \
    -p 1 \
    ./system_tests/ \
    -run 'TestEspresso'

gotestsum \
    --format short-verbose \
    --packages="github.com/offchainlabs/nitro/system_tests" \
    -- \
    -v \
    -timeout 35m \
    -p 1 \
    ./system_tests/ \
    -run 'TestCaffNode'
