[package]
name = "mel_machine_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
arbutil = { path = "../../arbutil/" }
prover = { path = "../../prover/" }
eyre = "0.6.5"
structopt = "0.3.23"
hex = { version = "0.4.3", features = ["serde"] }
clap = { version = "4.4.8", features = ["derive"] }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.67"
rayon = { version = "1.5.1" }

[workspace]
