name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/_build-release.yml
    with:
      workspace: true
      artifact-name: workspace-release-binaries
