name: coverage

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: llvm-cov
    runs-on: ocl-16cpu-64ram
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y build-essential clang libclang-dev cmake
      - uses: dtolnay/rust-toolchain@1.93
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest
      - name: Generate coverage report
        run: cargo llvm-cov nextest --workspace --lcov --output-path lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
