name: dependencies

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 0 * * 1" # every Monday

env:
  CARGO_TERM_COLOR: always

jobs:
  deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
