---
name: bold-legacy
on:
  workflow_call:

permissions:
  contents: read

jobs:
  bold-legacy:
    uses: ./.github/workflows/_go-tests.yml
    secrets: inherit
    with:
      run-name: bold-legacy
      run-legacy-challenge: true
