---
name: changelog
on:
  workflow_call:
    inputs:
      changelog_fragments:
        description: 'New changelog fragments.'
        required: true
        type: string

jobs:
  changelog-check:
    name: Check if changelog is updated
    runs-on: ubuntu-4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download unclog binary
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download v0.1.8 --repo OffchainLabs/unclog --pattern unclog --clobber

      - name: Check changelog fragments
        env:
          ALL_ADDED_MARKDOWN: ${{ inputs.changelog_fragments }}
        run: chmod +x unclog && ./unclog check -fragment-env=ALL_ADDED_MARKDOWN
