---
name: codecov
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
        description: Token to upload reports to Codecov. Required if `upload_report` is on.
    inputs:
      post_comment:
        description: 'Set to true to post a test summary comment on the PR.'
        type: boolean
        required: true
      upload_report:
        description: 'Set to true to upload test reports to Codecov.'
        type: boolean
        required: true
      report-name:
        description: 'Name to use when uploading reports to Codecov.'
        type: string
        required: false
        default: 'CI Test Results'

jobs:
  report_summary:
    name: Aggregate test results
    runs-on: ubuntu-4
    if: ${{ github.repository == 'OffchainLabs/nitro-private' }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download JUnit reports
        uses: actions/download-artifact@v7
        with:
          pattern: junit-reports-*
          path: downloaded-reports/

      - name: Upload test results to Codecov
        if: ${{ (inputs.post_comment && github.event_name == 'pull_request') || inputs.upload_report }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: 'downloaded-reports/'
          name: ${{ inputs.report-name }}
          report_type: test_results
