---
name: detect-file-changes

on:
  workflow_call:
    outputs:
      rust_changed:
        description: 'True if Rust files changed.'
        value: ${{ jobs.changes.outputs.rust_changed }}
      bold_legacy_changed:
        description: 'True if Bold Legacy or related files changed.'
        value: ${{ jobs.changes.outputs.bold_legacy_changed }}
      changelog_added:
        description: 'New changelog fragments.'
        value: ${{ jobs.changes.outputs.changelog_added }}

permissions:
  contents: read

jobs:
  changes:
    name: Detect file changes
    runs-on: ubuntu-4
    outputs:
      rust_changed: ${{ steps.changed.outputs.rust_any_changed }}
      bold_legacy_changed: ${{ steps.changed.outputs.bold_legacy_any_changed }}
      changelog_added: ${{ steps.changed.outputs.changelog_added_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PRIVATE_REPO_PAT || github.token }}
          fetch-depth: 10            # Will cover most PRs
          persist-credentials: true  # In case changed-files requires deeper depth

      - uses: ./.github/actions/init-submodules
        with:
          client-id: ${{ vars.NITRO_CI_APP_CLIENT_ID }}
          app-private-key: ${{ secrets.NITRO_CI_APP_PRIVATE_KEY }}
          pat: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Detect changes
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            rust:
              - 'crates/**'
              - 'contracts/**'
              - 'Makefile'
              - '**.toml'
              - '**/Cargo.lock'
              - '.github/workflows/_rust-tests.yml'
              - '.github/workflows/_detect-changes.yml'
            bold_legacy:
              - 'bold/legacy/**'
              - '.github/workflows/_bold-legacy.yml'
            changelog:
              - 'changelog/**.md'
