---
name: fast-ci-jobs
on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: arbitrator-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PRIVATE_REPO_PAT || github.token }}

      - uses: ./.github/actions/init-submodules
        with:
          app-id: ${{ vars.NITRO_CI_APP_ID }}
          app-private-key: ${{ secrets.NITRO_CI_APP_PRIVATE_KEY }}
          pat: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Setup CI
        uses: ./.github/actions/ci-setup

      - name: Build
        run: make -j8 build test-go-deps

      - name: Build all lint dependencies
        run: make -j8 build-node-deps

      - name: Setup CI
        uses: ./.github/actions/lint-go
