---
name: flaky-tests
on:
  workflow_call:

jobs:
  flaky-tests:
    name: Flaky Go tests
    runs-on: arbitrator-ci

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup CI
        uses: ./.github/actions/ci-setup

      - name: Set environment variables
        run: |
          mkdir -p target/tmp/deadbeefbee
          echo "TMPDIR=$(pwd)/target/tmp/deadbeefbee" >> "$GITHUB_ENV"
          echo "GOMEMLIMIT=6GiB" >> "$GITHUB_ENV"
          echo "GOGC=80" >> "$GITHUB_ENV"
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_ENV"

      - name: Build
        run: make -j8 build test-go-deps

      - name: Build all lint dependencies
        run: make -j8 build-node-deps

      - name: Run flaky tests
        continue-on-error: true
        run: >-
          ${{ github.workspace }}/.github/workflows/gotestsum.sh
          --tags cionly --timeout 60m --test_state_scheme hash --junitfile test-results/junit.xml --flaky

      - name: Process JUnit XML logs
        if: matrix.test-mode == 'defaults' && always()
        run: python3 ${{ github.workspace }}/.github/workflows/process_junit.py test-results/

      - name: Upload Go test Artifacts
        if: matrix.test-mode == 'defaults' && always()
        uses: actions/upload-artifact@v4
        with:
          name: go-junit-reports
          path: test-results/junit_*.xml
