---
name: standard-go-test-suite
on:
  workflow_call:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        test-mode: [defaults-A, defaults-B, flaky, pathdb-A, pathdb-B, consensus-execution-rpc-A, consensus-execution-rpc-B, challenge-A, challenge-B, stylus, l3challenge]
    uses: ./.github/workflows/_go-tests.yml
    secrets: inherit
    with:
      run-name: ${{ matrix.test-mode }}
      run-defaults-a: ${{ matrix.test-mode == 'defaults-A' }}
      run-defaults-b: ${{ matrix.test-mode == 'defaults-B' }}
      run-flaky: ${{ matrix.test-mode == 'flaky' }}
      run-pathdb-a: ${{ matrix.test-mode == 'pathdb-A' }}
      run-pathdb-b: ${{ matrix.test-mode == 'pathdb-B' }}
      run-consensus-execution-rpc-a: ${{ matrix.test-mode == 'consensus-execution-rpc-A' }}
      run-consensus-execution-rpc-b: ${{ matrix.test-mode == 'consensus-execution-rpc-B' }}
      run-challenge-a: ${{ matrix.test-mode == 'challenge-A' }}
      run-challenge-b: ${{ matrix.test-mode == 'challenge-B' }}
      run-stylus: ${{ matrix.test-mode == 'stylus' }}
      run-l3challenge: ${{ matrix.test-mode == 'l3challenge' }}
