name: Publish Nitro image

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  GITHUB_REGISTRY: ghcr.io

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  docker:
    name: Build and Push Nitro image
    runs-on: shared-large-01
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower-case repo name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Nitro image
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG="${{ github.event.release.tag_name }}"
          else
            TAG="latest"
          fi

          docker buildx build --target nitro-node --platform linux/amd64 -t ${{ env.GITHUB_REGISTRY }}/${REPO_LOWER}/nitro:${TAG} .
          docker push ${{ env.GITHUB_REGISTRY }}/${REPO_LOWER}/nitro:${TAG}
