---
name: Release CI
run-name: Release CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_run:
    runs-on: arbitrator-ci

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PRIVATE_REPO_PAT || github.token }}

      - uses: ./.github/actions/init-submodules
        with:
          client-id: ${{ vars.NITRO_CI_APP_CLIENT_ID }}
          app-private-key: ${{ secrets.NITRO_CI_APP_PRIVATE_KEY }}
          pat: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Startup Nitro testnode
        run: ./scripts/startup-testnode.bash
